project:
  type: website
  output-dir: _output
  render:
    - "2025-*.qmd"

execute:
  freeze: auto

bibliography: references.bib

#engines: ['julia']

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrartcl
    pdf-engine: lualatex
    include-in-header:
      text: |
          \usepackage{amsmath}
          \usepackage{amssymb}
          \usepackage{fontspec}
          \usepackage{polyglossia}
          \setmonofont{DejaVu Sans Mono}[Scale=MatchLowercase]
          \input{_common.tex}
